# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [6]:
standardized_X_test[0:10,]

array([[-0.46553666,  0.6181599 , -1.32341493, -1.04862124],
       [-1.57176239,  0.20142289, -1.38223338, -1.31409497],
       [ 0.9172455 , -0.00694562,  1.02932273,  0.80969488],
       [-0.74209309,  0.82652841, -1.32341493, -1.31409497],
       [-0.74209309, -0.84041964,  0.08822766,  0.27874742],
       [ 0.9172455 ,  0.20142289,  0.44113831,  0.41148428],
       [ 1.47035837, -0.21531412,  1.02932273,  1.20790548],
       [ 0.36413264, -1.88226218,  0.73523052,  0.41148428],
       [ 0.36413264, -0.84041964,  0.79404896,  0.54422115],
       [-0.88037131,  1.45163393, -1.32341493, -1.18135811]])

In [7]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [8]:
y_pred = perceptron.predict(standardized_X_test)

In [9]:
print(y_test)

[0 0 2 0 1 1 2 2 1 0 0 0 2 0 1 0 2 2 1 1 0 2 2 1 1 1 2 0 2 1]


In [10]:
print(y_pred)

[0 0 2 0 1 2 2 1 2 0 0 0 2 0 1 0 2 2 1 1 0 2 2 2 1 1 2 0 2 1]


In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.88      0.70      0.78        10
           2       0.75      0.90      0.82        10

    accuracy                           0.87        30
   macro avg       0.88      0.87      0.87        30
weighted avg       0.88      0.87      0.87        30

